FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4200

# Executa o Angular abrindo a escuta para conexões externas ao container
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]